feed_now:
  fields:
    device_id:
      required: false
      selector:
        text:
    tray_compartment_index:
      required: false
      selector:
        number:
          min: 1
          max: 4
    feed_duration_minutes:
      required: false
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
    heat_before_feeding:
      required: false
      selector:
        boolean:

add_schedule:
  fields:
    device_id:
      required: false
      selector:
        text:
    time:
      required: false
      selector:
        time:
    hour:
      required: false
      selector:
        number:
          min: 0
          max: 23
    minute:
      required: false
      selector:
        number:
          min: 0
          max: 59
    weekdays:
      required: false
      selector:
        object:
    enabled:
      required: false
      default: true
      selector:
        boolean:
    tray_compartment_index:
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 4
    feed_duration_minutes:
      required: false
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
    heat_before_feeding:
      required: false
      default: false
      selector:
        boolean:

sync_weekly_plan:
  fields:
    device_id:
      required: false
      selector:
        text:
    plan:
      required: true
      selector:
        object:
    replace:
      required: false
      default: true
      selector:
        boolean:

remove_schedule:
  fields:
    device_id:
      required: false
      selector:
        text:
    schedule_id:
      required: true
      selector:
        number:
          min: 0

set_schedule_enabled:
  fields:
    device_id:
      required: false
      selector:
        text:
    schedule_id:
      required: true
      selector:
        number:
          min: 0
    enabled:
      required: true
      selector:
        boolean:
